### PR TITLE
binary: Rewrite tests to use hspec with fail-fast.

### PR DESCRIPTION
**Pull request by rbasso**
- Rewrite tests to use hspec.
- Update tests to match the json file.
- Fix test descriptions mentioning "errors".

Related to #211.

### CODE REVIEW

**Comment by petertseng** [comment]
on the one hand, the behavior hasn't changed, so I shouldn't compain too much, but on the other hand, the tests now have descriptions that specifcally include the words "raises an error" yet an expectation of zero certainly isn't raising an error, so adding the descriptions makes the existing tests make less sense! Is it time to do something about this?

**Comment by rbasso** [comment]
Well....this came from `x-common`, so we could change it there.
But the exercise will be deprecated anyway, so It's not really important to update `x-common`.

I'll change the strings just to avoid the confusing error messages!

**Comment by rbasso** [comment]
Updated the descriptions mentioning *errors*

**Comment by petertseng** [comment]
:+1:

**Pull request merged**
