### PR TITLE
Adds an implementation of POV

### PR DESCRIPTION
**Pull request by alexkalderimis**
See exercism/x-common#70

### CODE REVIEW

**Comment by etrepum** [comment]
I think this might need to be rebased or something, the Merge pull request button is disabled.

**Comment by kytrinyx** [comment]
Yeah, I would suggest rebasing onto master, and then squashing the commits so that we get an atomic change. If you need help with the details of that holler.

**Comment by alexkalderimis** [comment]
@kytrinyx were you asking me to do that? If so, that's fine - I will see to it shortly.

**Comment by kytrinyx** [comment]
@alexkalderimis -- it's easiest if you do it, since it's on your branch, but if you don't have time we're always happy to fix it by resolving it locally.

**Comment by alexkalderimis** [comment]
Rebased as requested.

**Comment by etrepum** [comment]
Thanks! :+1:

**Pull request merged**
