### PR TITLE
binary-search-tree: Allow empty trees

### PR DESCRIPTION
**Pull request by petertseng**
Since #59 mentioned that it was surprising that binary search trees in this exercise couldn't be empty (since `bstValue` was of type `BST a -> a` rather than `BST a -> Maybe a`) I explored what it would be like if it was allowed.

Unfortunately, now that `data BST` has two variants and is no longer a record, we no longer get "free" implementations of `bstValue`, `bstLeft`, and `bstRight`. However, I found this better than the alternatives:

* `newtype BST a = BST (Maybe (Node a))` means you have to litter `fromBST` and `BST` in various places to convert to/from the `newtype`. I didn't particularly like this, but you can examine this at [my bst-empty-newtype branch](https://github.com/exercism/xhaskell/compare/master...petertseng:bst-empty-newtype?expand=1)
* `type BST a = Maybe (Node a)` works interestingly, but then I can't do the `Foldable` thing done here since the `Foldable` for `Maybe` didn't make sense for the `BST`, but `type` makes them indistinguishable.

As alluded to, since #59 mentions monoids, I made the example tree be an instance of `Foldable` so that the implementation of `toList` comes for free (along with other functions like `sum` and `product`)

See individual commit messages for more detail.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@towynlin You mentioned that you have both haskell experience and an interest in taking a look at things here on Exercism. Do you have a moment to review this?

**Comment by towynlin** [comment]
Yep, I'll take a look later today. Thanks for the contribution @petertseng, and thanks for pinging me @kytrinyx.

**Comment by towynlin** [comment]
Looks great to me! 👍 Thanks again for the detailed, thoughtful work @petertseng!

@kytrinyx I recommend merging the PR and closing #59.

**Comment by kytrinyx** [comment]
Thanks @towynlin and @petertseng!

**Pull request merged**
