### PR TITLE
Adding track specific documentation.

### PR DESCRIPTION
**Pull request by vguerra**

### CODE REVIEW

**Comment by kytrinyx** [comment]
For reference: https://github.com/exercism/rossconf/issues/11

**Comment by kytrinyx** [comment]
The haskell build is trying to run the tests for `docs/`

```
check-exercises.hs: /home/travis/build/exercism/xhaskell/./docs/example.hs: openFile: does not exist (No such file or directory)
```

Maybe there's a way to ignore the `docs` dir?

**Comment by vguerra** [comment]
@kytrinyx indeed there is =) .. just did .. seems like tests pass now.. I'll squash

**Comment by vguerra** [comment]
:+1:

**Comment by kytrinyx** [comment]
Excellent. Since this is a direct port from the existing documentation, I'll go ahead and merge. As these start getting used I'm sure we'll find ways of improving them :)

**Pull request merged**
