### PR TITLE
series: Rewrite tests to use hspec with fail-fast.

### PR DESCRIPTION
**Pull request by rbasso**
Related to #211.

### CODE REVIEW

**Comment by petertseng** [comment]
:+1:

**Comment by petertseng** [comment]
Do you think it would be instructive and/or useful to test that ```series 0 "" `shouldBe` [[]]``` and ```series 0 "hi" `shouldBe` [[]]```?  I felt strongly about testing size 0 in largest-series-product, but do not feel so strongly here.

**Comment by rbasso** [comment]
Your proposed tests seem correct to me.

Some submissions based on `Data.List.Split.divvy` would certainly break. Because it is implemented in what I humbly call *"the wrong way"*, but there is always a price for changes, and that's ok.

It's you call! If you write the PR, I'll certainly merge it. :smile:

**Comment by petertseng** [comment]
It's now ocurred to me to ask - what would the `divvy` solutions say that `series 0 ""` is?

**Comment by rbasso** [comment]
```
Prelude Data.List.Split> divvy 0 1 ""
[]
```

**Pull request merged**
