### PR TITLE
Add Stack instructions to installation.md

### PR DESCRIPTION
**Pull request by subshad**
This PR adds some installation instructions for the stack tool. It
explains briefly how to install stack (links to the stack
documentations) and how to use it to run the tests in each exercise.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thank you!

**Comment by rbasso** [comment]
The merge doesn't seem to affect the installation instructions at http://exercism.io/languages/haskell. I

Is this the expected behavior? Is there something else we should do, @kytrinyx ?

**Comment by petertseng** [comment]
That "something else" would be to update the submodule at https://github.com/exercism/x-api/tree/master/tracks

I usually wait for @kytrinyx to do it =D

**Comment by rbasso** [comment]
Got it! No rush! :sweat_smile:

**Comment by kytrinyx** [comment]
Oops. Yeah, sorry about that! There was a conference and I am always afraid of deploying when I won't be around to fix stuff if something should go wrong.

This is now deployed :)

**Comment by subshad** [comment]
Woo, first commit :smile: Thanks @rbasso @petertseng and @kytrinyx

**Pull request merged**
