### PR TITLE
Update config.json to new specification

### PR DESCRIPTION
**Pull request by Roshanjossey**
This addresses issue #274
https://github.com/exercism/xhaskell/issues/274

### CODE REVIEW

**Comment by petertseng** [comment]
I have verified that in 8e1ceb5 that "exercises" is ordered in the same way as "problems".

**Comment by rbasso** [comment]
Thank you! :smile:

**Comment by Roshanjossey** [comment]
@petertseng: I didn't understand why ordering of exercises is important in `exercises` key. As per the new changes, exercises will be fetched according to their order of difficulty right? As far as I understand ordering in `exercises` key is only relevant in the stage where `difficulty` of all exercises are `1`

**Comment by petertseng** [comment]
> As per the new changes, exercises will be fetched according to their order of difficulty right?

That was not my understanding of the plan as of https://github.com/exercism/discussions/issues/60#issuecomment-239740265 and https://github.com/exercism/discussions/issues/60#issuecomment-239968440 . It seems that the plan is to have exercises be fetched in the order they are listed in the file. Difficulty is not used in calculating when to fetch.

**Comment by Roshanjossey** [comment]
@petertseng: Thank you for clarifying that 👍

**Pull request merged**
