### PR TITLE
Add lens-person exercise

### PR DESCRIPTION
**Pull request by pminten**
This is a relatively easy exercise to play around with basic lenses. It's designed in such a way that lenses aren't actually required, so you can play around with different approaches and see what works best.

@etrepum I haven't made an x-common part for this yet since I wanted to get your opinion on this first. Do you think this is a good exercise for the Haskell track? It does kinda deviate from standard exercism practice by a) (strongly) suggesting the use of non-standard-library libraries and b) being clearly applicable only to Haskell.

### CODE REVIEW

**Comment by kytrinyx** [comment]
I think language-specific exercises are fine (they should still have an entry in the x-common, though perhaps with something in the config yml that says that it was conceived specifically for the haskell track.

I'm going to be working with some students this summer who will hopefully start using the metadata in x-common to start showing a bit of information about exercises on the site itself.

**Comment by pminten** [comment]
Build fails on lack of install lens lib. Anyone have objections to adding that to _test/bootstrap.sh?

**Comment by pminten** [comment]
@kytrinyx That's great. My experience is that the exercises which are most useful are often the more language (or at least paradigm) specific ones. The "translate the exercise" approach, practical as it may be, does tend to result in shoehorning.

**Comment by etrepum** [comment]
No objection to adding it to the bootstrap. I think having exercises designed for third party libraries is a good thing, particularly if they're de facto standards like lens. The Haskell world has changed in the past few years with cabal sandboxes, stackage and stack in a way that makes Haskell Platform much less relevant. We already depend on a number of packages that don't ship with GHC itself, so as long as it's clearly documented what the exercise needs I think it's fine.

**Comment by pminten** [comment]
Ok then, I'll add this tomorrow (don't have time / the right computer right now).

**Comment by etrepum** [comment]
:+1:

**Comment by pminten** [comment]
Build fixed, once the x-common PR is merged this one is ready to be merged here as well.

**Comment by etrepum** [comment]
Thanks! :+1:

**Pull request merged**
