### PR TITLE
Remove stub dependencies

### LINKED ISSUE #420: presenting clean package.yaml to students
Since #396 we can move our examples to a separate directory with its own `package.yaml` to prevent showing students extra elements in dependencies in `package.yaml`

Here are the current exercises with non-empty dependencies.

It should be pretty easy to script the process of moving them all at once. The question before doing that: Are there any exercises where we should just keep the `package.yaml` as-is?

- [ ] atbash-cipher: split
- [ ] bank-account: stm
- [ ] connect: array
- [ ] crypto-square: split
- [ ] food-chain: array
- [ ] go-counting: array
- [ ] grade-school: containers
- [ ] kindergarten-garden: containers, split
- [ ] largest-series-product: safe
- [ ] lens-person: lens
- [ ] linked-list: stm
- [ ] ocr-numbers: containers, split
- [ ] parallel-letter-frequency: parallel
- [ ] rna-transcription: containers
- [ ] robot-name: random
- [ ] saddle-points: containers
- [ ] say: array
- [ ] scrabble-score: containers
- [ ] sgf-parsing: attoparsec
- [ ] sieve: vector
- [ ] simple-cipher: random
- [ ] triangle: containers
- [ ] wordy: attoparsec, text

### PR DESCRIPTION
**Pull request by rbasso**
Closes #420.

### CODE REVIEW

**Comment by petertseng** [comment]
In case you are wondering, I have to delay the review of this until about 6 hours from now.

**Comment by petertseng** [comment]
But I can say this: Some of the commit messages say "unneeed" instead of "unneeded"

**Comment by petertseng** [comment]
the `lens-person` commit is labeled `largest-series-product`

**Comment by rbasso** [comment]
> But I can say this: Some of the commit messages say "unneeed" instead of "unneeded"

Most of them are wrong. I should not commit after 2AM. :grin: 
Fixed. :+1: 

> the lens-person commit is labeled largest-series-product

Thanks for finding that. :+1: 
Fixed.

**Comment by petertseng** [comment]
Checked and things seem to build. Thanks for going through these. Interesting thing I noticed: `kindergarten-garden`'s `Data.Map` requires `container`, but `go-counting`'s `Data.Set` doesn't? That's something I didn't expect. Do you know why?

**Comment by rbasso** [comment]
I think that `go-counting` dependencies on `containers` are in the global dependencies, probably because the test suite also depends on it.

```yaml
name: go-counting

dependencies:
  - base
  - containers

library:
  exposed-modules: Counting
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
    - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - go-counting
      - hspec
      - multiset
```

**Comment by petertseng** [comment]
Closes a flaw first discovered in https://github.com/exercism/xhaskell/pull/189#r70165604

**Pull request merged**
