### PR TITLE
travis: Install only the GHC we are testing

### LINKED ISSUE #119: travis: all builds install all GHC versions, rather than just the one they're testing
For example, the 7.6 build will install the 7.8 ghc and the 7.10 ghc. This may unnecessarily increase install times.

This can be avoided by specifying addons in the matrix, rather than on the top level.

### PR DESCRIPTION
**Pull request by petertseng**
This will decrease install times

Closes #119

### CODE REVIEW

**Comment by petertseng** [comment]
The various Travis PRs #118 #120 and #128 will probably have merge conflicts with each other. I can deal with them as the PRs are merged one by one.

**Comment by petertseng** [comment]
Hmm. Adds a bit of complexity (yaml references) to the yaml file. Saves about 8 seconds out of an 80 second build (if there's a cache hit) or a 5 minute build (if there's a cache miss). Though we run tests for every PR so I suppose it's good to save all the time we can. Plus, the savings are greater if we test more GHC versions (for example 8.0 as in #120, maybe even 7.4...)

**Comment by petertseng** [comment]
will rebase in next 24 hours. I can and should be prodded if not.

**Comment by petertseng** [comment]
I think github automatically sends notifications when I push new commits to a PR branch now, so notifications should have been sent. let me know whether that's true so I know whether I can safely stop notifying via comment

**Comment by rbasso** [comment]
I received the two notifications from your messages.

But don't worry! I'm checking it frequently.

**Comment by petertseng** [comment]
I'm just going to take a moment to say that I kept the cabal version at 1.22 across the board since this preserves existing behavior. I would note however that https://github.com/hvr/multi-ghc-travis/blob/master/make_travis_yml.hs has a map of GHC version to the cabal version at the time (well, excepting anything before 1.16, but that doesn't affect us) and usually tests the two together.

I don't have a strong opinion on what cabal version should be used, so I'll leave the existing behavior untouched unless there's a compelling reason to change.

**Pull request merged**
