### PR TITLE
say: Rewrite tests to use hspec with fail-fast.

### PR DESCRIPTION
**Pull request by rbasso**
Related to #211.

### CODE REVIEW

**Comment by petertseng** [comment]
Did not think we would have bounds that low! But it is not for me to question

:+1:

**Comment by rbasso** [comment]
> Did not think we would have bounds that low! But it is not for me to question

You can question anything! :smile:

Considering that there is no json for this exercise, we can change it as we like.

So, what would you like to change :question:

**Comment by petertseng** [comment]
I suppose what I really meant was: this PR is just the conversion from HUnit to HSpec, talking about changes to the tests can come separately! But here is an OK place I suppose, since the lines are getting changed anyway.

Two separate questions for us to answer:

* The upper limit doesn't have to be billions! Shall we also add trillion, quadrillions?
    * But, does that really add a lot to the exercise? Maybe not. If they can get thousand, million, billion, is adding trillion, etc. going to be that interesting? I suspect not.
    * Also https://github.com/exercism/x-common/blob/master/exercises/say/description.md says "it's fine to stop at trillion"
    * So I definitely say no to this.
* The lower limit doesn't have to be zero! Shall we add negative numbers? -1 could be "negative one", etc.
    * Does this add to the exercise? Maybe so. It is a new consideration that almost certainly is dealt with in a different way.
    * However it's not mentioned in https://github.com/exercism/x-common/blob/master/exercises/say/description.md ! So either we add it track-specific or we'd need to change the description in x-common.
    * I could be convinced to say yes to this, but I'm currently not feeling strongly.

**Comment by rbasso** [comment]
You are right, there is no reason to restrict the values.

I completely agree about dropping the upper limit, but I'm still unsure about the lower limit. Do you think that would add something interesting to the exercise?

If we decide to drop the lower limit too, there is no reason to return a `Maybe` anymore. How do you fell about it? Should we drop it too and remove the `Maybe`?

**Comment by petertseng** [comment]
Take my opinion with a grain of salt since I haven't done this exercise myself in any language. I do think negatives would be somewhat interesting (probably more interesting than going to trillions, quadrillions, etc.), but the question of whether it's interesting *enough* to be worth adding? Well, if unsure I'll suggest to try it! But I really don't feel strongly.

It may be the case that Maybe has to be kept though because no matter how far someone goes with trillions, quadrillions, etc. there still has to be a point at which they had to stop. Unless we expect solutions to be able to arbitrarily combine latin prefixes?!

**Comment by petertseng** [comment]
OK. On your recommendation that it would not be more interesting, then I suggest no more tests and merge as-is. If a preponderance of other track maintaners do decide to expand when someone creates say/canonical-data.json then we can consider.

**Comment by rbasso** [comment]
I removed the upper-limit test, but left the test for `-1` returning `Nothing` for now, until we discuss the negative inputs in `x-common`.

**Comment by petertseng** [comment]
Okay, so the idea is that this makes life better for the student - the student can now go to trillions if desired (the tests don't stop you now!) whereas before they could not.

OK

:+1:

**Comment by rbasso** [comment]
If you prefer I can drop the lower limit test too. I just would like to avoid, for now, to expect valid negative outputs.

**Comment by petertseng** [comment]
It's good as-is. Besides, if removed the lower limit test, then a student might ask "Why are all tests `Just`!"

**Pull request merged**
