### PR TITLE
Improved the tests by adding labels for each attack

### PR DESCRIPTION
**Pull request by alexkalderimis**
This pull request makes some minor improvements to the queen-attack tests by labelling each of the attacks so that failures can be diagnosed.

### CODE REVIEW

**Comment by etrepum** [comment]
:+1:

Did you know that you can run tests for an individual exercise by specifying it as a parameter to `./_test/check-exercises.hs`?

https://github.com/exercism/xhaskell/blob/master/_test/check-exercises.hs#L62-L64

**Comment by kytrinyx** [comment]
Maybe this would be worth mentioning in the SETUP.md.

**Comment by etrepum** [comment]
It's only relevant to folks working on the repo, and it is documented in the README https://github.com/exercism/xhaskell#running-tests

**Comment by kytrinyx** [comment]
Ah, right. Thanks!

**Pull request merged**
