### PR TITLE
hamming: Change return to Maybe and match json

### PR DESCRIPTION
**Pull request by rbasso**
- Change return type of `distance` to a *Maybe*.
- Rewrite tests to match `exercism/x-common/hamming.hs`.

### CODE REVIEW

**Comment by petertseng** [comment]
:+1:

**Comment by rbasso** [comment]
I think the `example.hs` is kind of ugly. Any idea to improve it?

**Comment by petertseng** [comment]
What would be closer to your ideal?

There is the option of checking the length beforehand instead of during, with something like:

```haskell
distance a b = if length a == length b then Just . sum . map fromEnum $ zipWith (/=) a b else Nothing
```

But this is pretty much just a little extra stuff slapped onto the previous solution. And this only work with `distance :: String -> String -> Maybe Int` rather than `distance :: Integral a => String -> String -> Maybe a` because `fromEnum` is `a -> Int`

(I also sometimes wonder whether it traverses `a` and `b` one more time than is necessary - one to find the length, then once more to compare them, but I don't know if everyone thinks about such things)

I may think of other ideas later, given some criteria

**Comment by petertseng** [comment]
You could move the `if x /= y` into a guard if you so desire.

**Comment by rbasso** [comment]
Thanks, @petertseng!

I also feel it traverses the lists two times, but I don't know enough to be sure.
I'll merge it the way it is. If you find any solution you think is good, just open the PR and I'll merge it. The same, of course, applies to other exercises. :+1:

**Comment by rbasso** [comment]
Just saw your last message.

**Pull request merged**
