### PR TITLE
series: rewrite to be flexible and improve stub.

### PR DESCRIPTION
**Pull request by rbasso**
- Change the test suite to accept multiple signatures.
- Add HINTS.md explaining how to work the exercise.
- Add a example solution using ByteStrings and Sequences.
- Add type signature to the stub solution.
- Add variables to the stub implementation.

These change also have the effect of allowing to run the test suite with the stub solution.

Related to #421.

### CODE REVIEW

**Comment by petertseng** [comment]
> These change also have the effect of allowing to run the test suite with the stub solution.

Oh, was it unable to before...?

Oh, indeed it was.

```
    • Ambiguous type variable ‘t0’ arising from a use of ‘shouldBe’
      prevents the constraint ‘(Eq t0)’ from being solved.
```

I see.

**Comment by petertseng** [comment]
I agree with every change I see here. Can I take a moment to be a stickler about separate commits?

I think one commit should be "improve stub", and the other commit everything else - everything else seems related, but "improve stub" seemed like the odd duck out in the big commit and seemed like it could go in its own commit. True, that would make the commit very small, but it seemed to make sense to me.

Unless you think the two I mentioned are inextricably linked, in which case sure, just tell me why and then merge it.

**Comment by rbasso** [comment]
You are right, they belong to separated commits. Fixed! :smile:

**Comment by petertseng** [comment]
Oh good, I can edit approve/request changes comments now (we were not able to before, which is why I always make it a separate comment)

**Pull request merged**
